theme: jekyll-theme-midnight

# staticman (comments) configuration
staticman_url: https://yume-red.herokuapp.com/v2/entry/harkdand/yume-comments/master

defaults:
  # Post defaults
    values:
      comments: true
